name: Ejercicio1

on: push
jobs:
  hola_mundo:
    runs-on: ubuntu-latest
    permissions:
      security-events: write


    steps:
      - name: Bajar codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with: 
          linter: pylint
